global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: dispatcher
    static_configs:
      - targets: ['dispatcher:9600']

  - job_name: worker
    metrics_path: /metrics
    static_configs:
      - targets: ['worker:9000']

  - job_name: socket_hub
    metrics_path: /metrics
    static_configs:
      - targets: ['socket-hub:8000']

  - job_name: redis_exporter
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: kafka_exporter
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: node_exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
